version: '3'

services:
  
  to_do_list_back:
    container_name: to_do_list_back
    build: 
      context: Back/ToDoListBack
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS : 'http://0.0.0.0:5000'
      DbHost :  'database_to_do'
      DbPort :  '5432'
      DbPass : '1'
      DbUserName : 'postgres'
    depends_on:
      - database_to_do
    ports:
      - 5001:5000
  
    
  to_do_list_front:
    container_name: to_do_list_front
    build: 
      context: Front
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - to_do_list_back
    
  
  
  
  
  
  database_to_do:
    image: postgres:14
    container_name: database_to_do
    restart: always
    ports:
      - 5434:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD : '1'
      POSTGRES_USER : 'postgres'
       
  robot_nginx:
    container_name: to_do_list_nginx
    image: nginx:alpine
    ports:
      - "8082:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    links:
      - to_do_list_front
    depends_on:
      - to_do_list_front
